### ISSUE TITLE
Don't follow the log by default

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#113]
When looking at a build which is still running, Jenkins follows the log automatically.
It's quite tricky to jump up and un-expand the log tab of the still running component, s.t. one can browse the other components.

**Comment by MartinNowak** [comment]
This is an upstream Jenkins issue that is hardly actionable on our side. Check https://issues.jenkins-ci.org/browse/. I've also made a PR that cleans up some scrolling, but it's too time intensive for me to work on this project.
https://github.com/jenkinsci/blueocean-plugin/pulls?q=is%3Apr+author%3AMartinNowak+is%3Aclosed

In general their whole codebase is an inefficient plugin mess and I'm looking at other/custom long-term alternatives. The tip on the ice-berg, besides the constant Java/Groovy/non-sense/doc annoyance, was that I have to delete old logs, because I'm currently at 60+GiB logs and **30+M** inodes. That works with BTRFS but it's not migratable to smaller instances.
