### ISSUE TITLE
Phobos PRs HEAD are tested, not their merge commit

### ISSUE THREAD

**Issue by Geod24** [dlang/ci#308]
See comment [here](https://github.com/dlang/phobos/pull/6705#issuecomment-420156579).

Phobos broke because a PR was merged when it was green, but the resulting master build was red.
That PR (incorrectly) changed the Makefile target `buildkite-test` to use `betterC` instead of `betterc` (which had changed on master but not on stable).

**Comment by wilzbach** [comment]
I'm not sure what the bug here is. The PR was red when merged:

![image](https://user-images.githubusercontent.com/4370550/47211051-d1022780-d394-11e8-84f0-8d1847dd43a4.png)

We should probably make Buildkite just stable enough, s.t. it can be a required check, but with it testing all the projects there are just too many potential error sources :/

**Comment by Geod24** [comment]
@wilzbach : Look at the failure. It was failing `libmir/random`, not `Phobos`. After the merge, Phobos started to fail. Same for my PR. It was red when tested, then green after merge.

**Comment by wilzbach** [comment]
Oh sorry. Here's  how the log looks like:

![image](https://user-images.githubusercontent.com/4370550/47212054-774f2c80-d397-11e8-8597-051510fb19cf.png)

https://buildkite.com/dlang/phobos/builds/336#00a303b3-1fcc-4796-82b9-4a4e8a0325a6

So we correctly checkout `refs/pull/6677/merge` from GitHub. That's the reference in which they merge the PR into the target branch.

**Comment by wilzbach** [comment]
Oh sorry. That was for the "Style" target, we don't seem to do this for "Phobos".

**Comment by wilzbach** [comment]
Fix: https://github.com/dlang/ci/pull/323
