### ISSUE TITLE
Test building DMD with itself?

### ISSUE THREAD

**Issue by skl131313** [dlang/ci#83]
Might be a good idea to build DMD with itself to ensure it can build itself fine. Can't seem to build a valid release version with the latest DMD.

**Comment by wilzbach** [comment]
We already do that on all CIs (Travis, Circle Ci, DAutoTest, auto-tester, and even here). 
So I am pretty sure that the problem is on your side. What error do you get? IIRC there is a problem with the layout of the released binary archive which makes it a bit more difficult to build the compiler. Have you tried building DMD directly from GitHub?

(Please feel free to ask further questions at the NG: D.learn)

**Comment by skl131313** [comment]
Problem is on Windows and from what I'm aware the only one that runs tests for Windows is auto-tester. From one of the builds it looks to be using an old compiler version, by mistake as it sets HOST_DC twice. Seems to be using 2.068.2, if the path is to be trusted.

```
HOST_DC=/home/braddr/sandbox/at-client/release-build/install/windows/bin/dmd.exe
HOST_DC=C:\cygwin\home\braddr\sandbox\at-client\release-build\dmd-2.068.2\windows\bin\dmd.exe
```
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=129223&dataid=895523
